import { isValidElement, useEffect, useId, useState, type ReactNode } from "react";
import Markdown, { type Components } from "react-markdown";
import remarkGfm from "remark-gfm";

// Preprocess markdown to handle table pipes commonly generated by AI agents inside list items.
// remark-gfm requires block-level separation (blank line) before tables; without it the pipe
// rows are treated as paragraph text inside list items instead of rendered as a table.
function preprocessMarkdown(md: string): string {
  const lines = md.split("\n");
  const result: string[] = [];
  let i = 0;

  while (i < lines.length) {
    const trimmed = lines[i].trimStart();

    // Case 1: \| escaped pipes — AI agents sometimes escape pipes inside lists.
    // Strip the backslash and lift to block-level table.
    if (trimmed.startsWith("\\|")) {
      const tableLines: string[] = [];
      let j = i;
      while (j < lines.length && lines[j].trimStart().startsWith("\\|")) {
        tableLines.push(lines[j].trimStart().substring(1));
        j++;
      }
      if (tableLines.length >= 2) {
        if (result.length > 0 && result[result.length - 1].trim() !== "") {
          result.push("");
        }
        result.push(...tableLines, "");
        i = j;
        continue;
      }
    }

    // Case 2: Plain | pipe rows immediately after non-blank non-table content.
    // This happens when AI writes a table right after a list item with no blank line.
    // Inject a blank line so remark-gfm treats the table as a block-level element.
    if (trimmed.startsWith("|") && result.length > 0) {
      const lastLine = result[result.length - 1].trim();
      if (lastLine !== "" && !lastLine.startsWith("|")) {
        result.push("");
      }
    }

    result.push(lines[i]);
    i++;
  }

  return result.join("\n");
}
import { cn } from "../lib/utils";
import { useTheme } from "../context/ThemeContext";
import { mentionChipInlineStyle, parseMentionChipHref } from "../lib/mention-chips";

interface MarkdownBodyProps {
  children: string;
  className?: string;
  /** Optional resolver for relative image paths (e.g. within export packages) */
  resolveImageSrc?: (src: string) => string | null;
}

let mermaidLoaderPromise: Promise<typeof import("mermaid").default> | null = null;

function loadMermaid() {
  if (!mermaidLoaderPromise) {
    mermaidLoaderPromise = import("mermaid").then((module) => module.default);
  }
  return mermaidLoaderPromise;
}

function flattenText(value: ReactNode): string {
  if (value == null) return "";
  if (typeof value === "string" || typeof value === "number") return String(value);
  if (Array.isArray(value)) return value.map((item) => flattenText(item)).join("");
  return "";
}

function extractMermaidSource(children: ReactNode): string | null {
  if (!isValidElement(children)) return null;
  const childProps = children.props as { className?: unknown; children?: ReactNode };
  if (typeof childProps.className !== "string") return null;
  if (!/\blanguage-mermaid\b/i.test(childProps.className)) return null;
  return flattenText(childProps.children).replace(/\n$/, "");
}

function MermaidDiagramBlock({ source, darkMode }: { source: string; darkMode: boolean }) {
  const renderId = useId().replace(/[^a-zA-Z0-9_-]/g, "");
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;
    setSvg(null);
    setError(null);

    loadMermaid()
      .then(async (mermaid) => {
        mermaid.initialize({
          startOnLoad: false,
          securityLevel: "strict",
          theme: darkMode ? "dark" : "default",
          fontFamily: "inherit",
          suppressErrorRendering: true,
        });
        const rendered = await mermaid.render(`paperclip-mermaid-${renderId}`, source);
        if (!active) return;
        setSvg(rendered.svg);
      })
      .catch((err) => {
        if (!active) return;
        const message =
          err instanceof Error && err.message
            ? err.message
            : "Failed to render Mermaid diagram.";
        setError(message);
      });

    return () => {
      active = false;
    };
  }, [darkMode, renderId, source]);

  return (
    <div className="paperclip-mermaid">
      {svg ? (
        <div dangerouslySetInnerHTML={{ __html: svg }} />
      ) : (
        <>
          <p className={cn("paperclip-mermaid-status", error && "paperclip-mermaid-status-error")}>
            {error ? `Unable to render Mermaid diagram: ${error}` : "Rendering Mermaid diagram..."}
          </p>
          <pre className="paperclip-mermaid-source">
            <code className="language-mermaid">{source}</code>
          </pre>
        </>
      )}
    </div>
  );
}

import { remarkGemIssues } from "../lib/remark-gem-issues";

export function MarkdownBody({ children, className, resolveImageSrc }: MarkdownBodyProps) {
  const { theme } = useTheme();
  const components: Components = {
    pre: ({ node: _node, children: preChildren, ...preProps }) => {
      const mermaidSource = extractMermaidSource(preChildren);
      if (mermaidSource) {
        return <MermaidDiagramBlock source={mermaidSource} darkMode={theme === "dark"} />;
      }
      return <pre {...preProps}>{preChildren}</pre>;
    },
    table: ({ node: _node, children: tableChildren, ...tableProps }) => (
      <div className="paperclip-markdown-table-wrapper">
        <table {...tableProps}>{tableChildren}</table>
      </div>
    ),
    a: ({ node: _node, href, children: linkChildren, className, ...props }: any) => {
      const parsed = href ? parseMentionChipHref(href) : null;
      if (parsed) {
        const targetHref = parsed.kind === "project"
          ? `/projects/${parsed.projectId}`
          : `/agents/${parsed.agentId}`;
        return (
          <a
            href={targetHref}
            className={cn(
              "paperclip-mention-chip",
              `paperclip-mention-chip--${parsed.kind}`,
              parsed.kind === "project" && "paperclip-project-mention-chip",
              className
            )}
            data-mention-kind={parsed.kind}
            style={mentionChipInlineStyle(parsed)}
            {...props}
          >
            {linkChildren}
          </a>
        );
      }
      return (
        <a href={href} rel="noreferrer" className={className} {...props}>
          {linkChildren}
        </a>
      );
    },
    input: ({ node: _node, type, checked, disabled, ...inputProps }) => {
      if (type === "checkbox") {
        return (
          <input
            {...inputProps}
            type="checkbox"
            defaultChecked={checked}
            className="paperclip-task-checkbox cursor-pointer mr-1.5 align-middle"
          />
        );
      }
      return <input type={type} checked={checked} disabled={disabled} {...inputProps} />;
    },
  };
  if (resolveImageSrc) {
    components.img = ({ node: _node, src, alt, ...imgProps }) => {
      const resolved = src ? resolveImageSrc(src) : null;
      return <img {...imgProps} src={resolved ?? src} alt={alt ?? ""} />;
    };
  }

  return (
    <div
      className={cn(
        "paperclip-markdown prose prose-sm max-w-none break-words overflow-hidden",
        theme === "dark" && "prose-invert",
        className,
      )}
    >
      <Markdown remarkPlugins={[remarkGfm, remarkGemIssues]} components={components} urlTransform={(url) => url}>
        {preprocessMarkdown(children)}
      </Markdown>
    </div>
  );
}
